#!/bin/bash


#Author: Nida Bastürk
#Date: 23.05.2024
#Modified (Laura)


# Function: seqkit_run
# Description: Extracts ROI from genome FASTA files using SeqKit
#
# This function processes BED files containing ROI information and uses
# SeqKit to extract these regions from the corresponding genome FASTA files. 
# The extracted sequences are then saved as separate FASTA files.
#
# Usage: seqkit_run <input_bed_dir> <input_fasta_dir> <output_ROI_dir> <gene_to_annotate> [threads]
#
# Parameters:
#   $1 (input_bed_dir): Directory containing BED files with ROI information
#   $2 (input_fasta_dir): Directory containing input genome FASTA files
#   $3 (output_ROI_dir): Directory where extracted ROI FASTA files will be saved
#   $4 (gene_to_annotate): Name of the genes of interest to be annotated, used to label output files (Example: "NKG2")  
#   $5 (threads): Optional. Number of threads for parallel processing (default: 4)
#
# Example:
#   seqkit_run "/path/to/bed_files" "/path/to/fasta_files" "/path/to/output_ROI" "NKG2" 4
#
# Notes: Ensure that SeqKit is installed and accessible in the current environment


seqkit_run(){
    local input_bed_dir="$1"
    local input_fasta_dir="$2"
    local output_ROI_dir="$3"
    local gene_to_annotate="$4"
    local threads="${5:-false}"
    
    # Run seqkit for each bed file
    for bed_file in "$input_bed_dir"/*
    do 
        genome_name=$(cat ${bed_file} | cut -f4)
        contig_name=$(cat ${bed_file} | cut -f1)
        
        # Dynamically find the matching file for genome_name
        fasta_file=$(compgen -G "$input_fasta_dir/${genome_name}.*")
        echo $fasta_file
        
        # Check if a matching file exists
        if [[ -z "$fasta_file" ]]; then
            echo "No matching FASTA file found for genome: $genome_name in $input_fasta_dir"
            continue
        fi

        # Prepare the seqkit command
        local cmd="seqkit subseq \"$fasta_file\" --bed \"$bed_file\""
        
        # Add threads option if specified
        if [[ "$threads" != "false" && "$threads" =~ ^[0-9]+$ ]]; then
            cmd+=" -j $threads"
        fi
        
        # Run seqkit
        eval $cmd > "$output_ROI_dir/${genome_name}_${gene_to_annotate}_${contig_name}_ROI.fasta"
        
        # Cleanup: Remove .seqkit.fai file generated by seqkit
        rm -f "${fasta_file}.seqkit.fai"
    done
}

# Export the function so it can be called from outside the script
export -f seqkit_run
