#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 25 20:07:00 2024

@author: lahumada
"""

# This script uses regular expressions to find the stretches of Ns
# in a fasta sequence and then creates a GFF3 file with the coordinates
# to the stretches of Ns.

# Main function: create_N_annotation_gff3_all_files(single_contig_list, input_fasta_dir, output_gff3_dir)

from Bio import SeqIO 
import os
import re



# Function to find the Ns and write the N annotations in a gff3 file       
def create_N_annotation_gff3 (fasta_file, gff3_file):    
    '''
    Create GFF3 annotation files for the ambiguous base (N) stretches in the 
    ROI FASTA sequence using SeqIO. Each stretch of Ns will have an annotation
    entry in the resulting GFF3 file.
    	- fasta_file: FASTA file input containing the raw region of interest to be annotated
    	- gff3_file: GFF3 file output to save the annotated sequence gaps
    '''
    # read fasta file
    for record in SeqIO.parse(fasta_file, "fasta"):
        fasta_entry_name = record.id
        sequence = str(record.seq)
        
        # Find all stretches of Ns and save coordinates in n_annotation variable
        # r -> raw string to avoid using scape characters
        # 'N+' -> regular expression pattern, character N or more consecutive occurrences of the character
        n_annotation = re.finditer(r'N+', sequence, re.IGNORECASE)
        print("Find N stretches")
    
        # Create and open gff3 file
        with open(gff3_file, 'w') as file:
            # write header 
            file.write("##gff-version 3\n")
        
            # write annotations for each n stretch
            for i, n_annotation_entry in enumerate(n_annotation, start=1):
                start = n_annotation_entry.start() + 1  # gff3 is 1-indexed
                end = n_annotation_entry.end()
                length = end - start + 1
            
                file.write(f"{fasta_entry_name}\tannotate_N_stretches\tN_stretch\t{start}\t{end}\t.\t+\t.\tID=N_stretch_{i};Name=N_stretch_{i};Length={length}\n")
                print(f"Write in gff3 entry N_stretch_{i}")

            

def create_N_annotation_gff3_all_files(single_contig_list, input_fasta_dir, output_gff3_dir):
    """Loop the create_N_annotation_gff3 function over all the input ROI FASTA files
    	- single_contig_list: TXT file list of genome with flanking genes in a single contig
    	- input_fasta_dir: Directory containing FASTA files with the raw genomic region of interest
    	- ouput_gff3_dir: Directory to save the GFF3 files generated by this script with the annotation of sequence gaps
    """
    # Read genome file to a list
    genome_file = open(single_contig_list,'r')
    genome_list = genome_file.readlines() 

    # List the files in fasta directory
    files_ROI = os.listdir(input_fasta_dir)
    files_ROI.sort()


    # Loop over the genome and run the function to annotate Ns
    for genome in genome_list:
        # Strip the genome names from the last character (\n)
        genome = genome.strip()
        print(genome)
    
        # Name for the gff3 file:
        gff3_name = f"{genome}_annotate_N_stretches.gff3"
        # Path to the gff3 file for a genome
        gff3_file = os.path.join(output_gff3_dir, gff3_name)
    
        # Find name for ROI file for a genome
        fasta_name = [item for item in files_ROI if genome in item]

        # Path to the fasta file for a genome
        fasta_file = os.path.join(input_fasta_dir, fasta_name[0])
    
        # Run function
        create_N_annotation_gff3(fasta_file, gff3_file)
