#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  3 22:27:16 2021

@author: lahumada
"""

##################
# This script extracts the flanking information relevant for extracting the
# ROI with seqkit from the flanking alignment output from GMAP
# Write the data for seqkit in one BED file per genome

# Main function: extract_seqkit_data_all_file(input_gmap, output_seqkit)

import os
from .read_gff3_to_df import read_gff3  #Custom function to read gff3



# Function that extracts the data for seqkit and makes a BED file per genome
def extract_seqkit_data(filepath, output_seqkit):
    ''' 
    Extract from GFF3 annotation files, produced by GMAP alignment of flanking genes
    to FASTA genome files, the necessary data to parse to SeqKit and extract the ROI
    from the genome files and write it on a BED file per genome.
    Information extracted about the location of the ROI: chromosome, min coordinate, max coordinate, genome
    	- filepath: GFF3 file generated by GMAP
    	- output_seqkit: Directory to save BED files with data to be used in seqkit to extract ROI
    '''
    gmap_gff3_file = read_gff3(filepath)
    
    # Remove the columns that Im not interested in:
    gmap_gff3_file = gmap_gff3_file.drop(columns=[5,7,8])
    # Remove the rows with nans
    gmap_gff3_file = gmap_gff3_file.dropna()
    # Name columns
    gmap_gff3_file.columns = ['chr', 'genome', 'gene', 'start', 'end', 'sense']
    # Remove columns that have this words: 'mRNA','exon', 'CDS'
    gmap_gff3_file = gmap_gff3_file[~gmap_gff3_file['gene'].isin(['mRNA','exon','CDS'])]
    # pandas reads ints as floats. Convert back to ints
    gmap_gff3_file.start = gmap_gff3_file.start.astype(int)
    gmap_gff3_file.end = gmap_gff3_file.end.astype(int)
    # Find the max and min value of the entire dataframe
    max_ROI = gmap_gff3_file[['start','end']].max().max()
    min_ROI = gmap_gff3_file[['start','end']].min().min()
    # Convert both integers into strings
    max_ROI = str(max_ROI)
    min_ROI = str(min_ROI)
    # Find the contig/scaffold/chromosome name
    chr_ROI = gmap_gff3_file.iloc[0,0]
    # Find the genome name
    genome_ROI = gmap_gff3_file.iloc[1,1]

    # Make a list with the genome, chromosome, min an max data
    data_seqkit = [chr_ROI, min_ROI, max_ROI, genome_ROI]

    # Write the data for seqkit in a new file:
    genome_bed_file = f"{genome_ROI}.bed"
    flanking_data_gmap_for_seqkit = os.path.join(output_seqkit, genome_bed_file)
   
    # Append a list to a file
    with open(flanking_data_gmap_for_seqkit, "w") as new_file:
        # Append text at the end of file
        for element in data_seqkit:
            new_file.write(element + '\t')
        
        
def extract_seqkit_data_all_file(input_gmap, output_seqkit):
    """Loop the extract_seqkit_data function over all the files created by GMAP for each genome
    	- input_gmap: Directory to GMAP GFF3 annotation files with the flanking genes
    	- output_seqkit: Directory to save BED files with data to be used in seqkit to extract ROI
    """
    # Loop the function on the gff3 files created by gmap (genome vs ROI flanking regions)
    for filename in os.listdir(input_gmap):
        filepath = os.path.join(input_gmap, filename)
        extract_seqkit_data(filepath, output_seqkit)
